version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    command: sh startup.sh
    volumes:
      - ./:/src
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/payments
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A app.background_tasks.celery worker --loglevel=info
    volumes:
      - ./:/src
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/payments
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker

  postgres:
    container_name: postgres-db
    image: 'postgres:15.3-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments