FROM python:3.11.4-alpine3.18

WORKDIR /app

COPY ./pyproject.toml /app/pyproject.toml

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install 

COPY . .
