version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./app:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A background_tasks.celery worker --loglevel=info
    volumes:
      - ./app:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:latest

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker