"""empty message

Revision ID: 02269cc0a416
Revises: 
Create Date: 2023-07-31 00:03:29.332303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02269cc0a416'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_slip',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('government_id', sa.String(length=11), nullable=False),
    sa.Column('debt_amount', sa.Double(precision=10), nullable=False),
    sa.Column('debt_due_date', sa.Date(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('paid_by', sa.String(length=255), nullable=True),
    sa.Column('paid_amount', sa.Double(precision=10), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_debit_id'), 'bank_slip', ['debt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_debit_id'), table_name='bank_slip')
    op.drop_table('bank_slip')
    # ### end Alembic commands ###
